# permissions for end users to view hoges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hoge-viewer-role
rules:
- apiGroups:
  - samplecontroller.example.com
  resources:
  - hoges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samplecontroller.example.com
  resources:
  - hoges/status
  verbs:
  - get
