# permissions for end users to edit hoges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hoge-editor-role
rules:
- apiGroups:
  - samplecontroller.example.com
  resources:
  - hoges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplecontroller.example.com
  resources:
  - hoges/status
  verbs:
  - get
